// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvM-dKNHFjnHDZNJuiJ4H_BvSsVfDZfq0',
    appId: '1:800607926136:web:ba1280b7be48c6ace03a8d',
    messagingSenderId: '800607926136',
    projectId: 'kisiselbutceapp',
    authDomain: 'kisiselbutceapp.firebaseapp.com',
    storageBucket: 'kisiselbutceapp.appspot.com',
    measurementId: 'G-1PHK3N9VJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdJCh3x4ugqM5M-UJkfI4Pj0V92ucDGkw',
    appId: '1:800607926136:android:192fbde891eb786fe03a8d',
    messagingSenderId: '800607926136',
    projectId: 'kisiselbutceapp',
    storageBucket: 'kisiselbutceapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ4Ws-DXkq4jKn9t5vX3FUGLr-TzMywFg',
    appId: '1:800607926136:ios:12c9fb84663264eae03a8d',
    messagingSenderId: '800607926136',
    projectId: 'kisiselbutceapp',
    storageBucket: 'kisiselbutceapp.appspot.com',
    iosClientId: '800607926136-74obf7604q04td116679j6n1ccrhc3u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.kisiselButceYonetimi',
  );
}
